get_one_file_size.Rmd:
  path: dev/get_one_file_size.Rmd
  state: active
  R: R/get_one_file_size.R
  tests: tests/testthat/test-get_one_file_size.R
  vignettes: vignettes/taille-des-fichiers.Rmd
  inflate:
    flat_file: dev/get_one_file_size.Rmd
    vignette_name: Taille des fichiers
    open_vignette: true
    check: true
    document: true
    overwrite: ask
