# WARNING - Generated by {fusen} from dev/get_one_file_size.Rmd: do not edit by hand

test_that("get_one_file_size works",{

nrowsquirrels <- get_one_file_size(system.file("nyc_squirrels_sample.csv", package = "toolboxfilebenoit")
)
  expect_equal(nrowsquirrels[["size"]],
               118993)
})
