# WARNING - Generated by {fusen} from dev/get_one_file_size.Rmd: do not edit by hand

#' Obtenir la taille d'un fichier
#'
#' @param path A string : path of the file to be analysed.
#'
#' @return df_filesize A `data.frame` : name and size of the file pointed by `path`.
#' @export
#'
#' @examples
#'
#'
#' # Example with your dataset in "inst/"
#' datafile <- system.file("nyc_squirrels_sample.csv", package = "fusen")
#'
#' get_one_file_size(datafile)
#' # data(sampledf)
#' # 
#' # temp_path <- tempfile(pattern = "test_filesize")
#' # temp_filepath <- file.path(temp_path,"sampledf.csv" )
#' # write.csv(x = sampledf, temp_filepath) 
#' # get_one_file_size(sampledf)
#'
#'
get_one_file_size <- function(path) {
  
filesize <- file.size(path)
filename <- basename(path)

df_filesize <- data.frame(name = filename, size = filesize ) 
return(df_filesize)
}
